name: Fetch AWS Provider Changes
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and filter changelog
        run: |
          curl -s https://raw.githubusercontent.com/hashicorp/terraform-provider-aws/refs/heads/main/CHANGELOG.md | \
          awk '
          BEGIN {
            printing = 0
            section = ""
          }
          /^## [0-9]+\.[0-9]+\.[0-9]+/ {
            print "\n" $0 "\n"
            printing = 1
            next
          }
          /^FEATURES:/ {
            if (printing) {
              print "\nFEATURES:"
              section = "FEATURES"
            }
            next
          }
          /^ENHANCEMENTS:/ {
            if (printing) {
              print "\nENHANCEMENTS:"
              section = "ENHANCEMENTS"
            }
            next
          }
          /^BUG FIXES:/ {
            if (printing) {
              print "\nBUG FIXES:"
              section = "BUG FIXES"
            }
            next
          }
          /^NOTES:/ {
            if (printing) {
              print "\nNOTES:"
              section = "NOTES"
            }
            next
          }
          /rds|dynamodb|docdb|[^a-zA-Z]db[^a-zA-Z]|redshift|aurora/ {
            if (printing && section != "") {
              print $0
            }
          }
          ' > changes.md

      - name: Check if changes exist
        id: check_changes
        run: |
          if [ -s changes.md ] && [ -n "$(git status --porcelain changes.md)" ]; then
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          else
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.changes_exist == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add changes.md
          git commit -m "Update changes.md with filtered changelog entries"
          git push || echo "No changes to commit"

      - name: Create issue if changes exist
        if: steps.check_changes.outputs.changes_exist == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const changes = fs.readFileSync('changes.md', 'utf8');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New AWS Provider Changes Detected',
              body: 'New changes have been detected in the AWS Provider Changelog:\n\n```\n' + changes + '\n```'
            });
