name: Fetch AWS Provider Changes
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  fetch-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and filter changelog
        run: |
          curl -s https://raw.githubusercontent.com/hashicorp/terraform-provider-aws/refs/heads/main/CHANGELOG.md | \
          grep -iE 'rds|dynamodb|docdb|[^a-zA-Z]db[^a-zA-Z]|redshift|aurora|enhancement|feature|bug fixes' > changes.md

      - name: Check if changes exist
        id: check_changes
        run: |
          if [ -s changes.md ]; then
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          else
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.changes_exist == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add changes.md
          git commit -m "Update changes.md with filtered changelog entries"
          git push

      - name: Create issue if changes exist
        if: steps.check_changes.outputs.changes_exist == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const changes = fs.readFileSync('changes.md', 'utf8');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New AWS Provider Changes Detected',
              body: 'New changes have been detected in the AWS Provider Changelog:\n\n```\n' + changes + '\n```'
            });
